export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAILIURE = "CATEGORY_LIST_FAILIURE";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";