export const theme ={
    Text:{
        default:'black',
        primary:'grey',
        secondary:'green'
    },
    background:{
        main:'#FFFF00',
        primary:'#197A56',
    },
    size:{
        xs:'0.4rem',
        sm:'0.3rem',
        md:'0.5rem',
        lg:'1rem',
        exlg:'1.25rem',
        ex2lg:'1.5rem',
        ex3lg:'1.75rem',
        ex4lg:'3rem'
    },
    color:{
        primary:'red',
        secondary:'blue',
        default:'black'
    },
    bordersize:{
        xs:'0.4rem',
        sm:'0.3rem',
        md:'0.5rem',
        lg:'1rem',
        exlg:'1.25rem',
        ex2lg:'1.5rem',
        ex3lg:'1.75rem',
        ex4lg:'2rem'
    }
}