export const theme ={
    Text:{
        default:'black',
        primary:'grey',
        secondary:'green'
    },
    background:{
        main:'#f2f2f266',
        primary:'#197a56',
    },
    size:{
        xs:'0.4rem',
        sm:'0.3rem',
        md:'0.5rem',
        lg:'1rem',
        exlg:'1.25rem',
        ex2lg:'1.5rem',
        ex3lg:'1.75rem',
        ex4lg:'2rem'
    },
    color:{
        primary:'red',
        secondary:'blue',
        default:'green'
    },
    bordersize:{
        xs:'0.4rem',
        sm:'0.3rem',
        md:'0.5rem',
        lg:'1rem',
        exlg:'1.25rem',
        ex2lg:'1.5rem',
        ex3lg:'1.75rem',
        ex4lg:'2rem'
    },
    borderadius:{
        xs:'0.4rem',
        sm:'0.3rem',
        md:'0.5rem',
        lg:'1rem',
    },

}